# Generated by Django 4.1 on 2022-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('faculty', models.CharField(max_length=100)),
                ('points_requirements', models.IntegerField()),
                ('subject_requirements', models.CharField(max_length=300)),
                ('course_description', models.TextField()),
                ('careers_offered', models.TextField()),
            ],
        ),
    ]
