# Generated by Django 4.1 on 2022-09-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_fcal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fcal',
        ),
    ]
