# Generated by Django 4.1 on 2023-03-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_fcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subjects_studied', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='degree',
            name='course_name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
