# Generated by Django 4.1 on 2023-03-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_subjects_remove_courses_id_remove_degree_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
